v = input('Digite algo: ')
print('Tipo primitivo: ', type(v))
print('É um número?', v.isnumeric())
print('É alfabético?', v.isalpha())
print('É alfanumérico?', v.isalnum())
print('Está em maiúsculas?', v.isupper())
print('Está em minúsculas?', v.islower())
print('Está capitalizada?', v.istitle())
print('É um espaço?', v.isspace())
print('É um dígito?', v.isdigit())
print('É um identificador?', v.isidentifier())
print('É imprimível?', v.isprintable())